spring:
    datasource:
        url: jdbc:mysql://localhost:3306/sms-saas-db
        username: root
        password: 12345678
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        hibernate:
            ddl-auto: update
        database: mysql
        open-in-view: false

jwt:
    duration: 1
    secret-key: 70655367566B5970347336763979244226452948404D635166546A576D5A7164
    